-- Creación Base de datos

CREATE DATABASE project;


-- Creación tablas

CREATE TABLE CUSTOMERS (
id SERIAL PRIMARY KEY,
name VARCHAR(100),
phone VARCHAR(10)
);

CREATE TABLE BRANCHES (
id SERIAL PRIMARY KEY,
name VARCHAR(100),
address VARCHAR(256)
);

CREATE TABLE ORDERS (
id SERIAL PRIMARY KEY,
customer_id INTEGER,
branch_id INTEGER,
order_date TIMESTAMPTZ,
total NUMERIC(10,2)
);

CREATE TABLE STOCKS (
id SERIAL PRIMARY KEY,
branch_id INTEGER NOT NULL,
product_id INTEGER NOT NULL,
quantity INTEGER,
CONSTRAINT product_branch UNIQUE (branch_id, product_id)
);

CREATE TABLE ITEMS (
id SERIAL PRIMARY KEY,
order_id INTEGER,
product_id INTEGER,
quantity INTEGER,
sale_amount NUMERIC(10,2)
);

CREATE TABLE PRODUCTS (
id SERIAL PRIMARY KEY,
name VARCHAR(100),
brand VARCHAR(100),
category_id INTEGER,
unit_price NUMERIC(10,2)
);

CREATE TABLE CATEGORIES (
id SERIAL PRIMARY KEY,
name VARCHAR(100)
);
